import type { ActivityEvent } from "@/lib/types";

export const mockActivity: ActivityEvent[] = [
  {
    id: "activity-1",
    type: "commit",
    repository: "devanalytics-dashboard",
    description: "Pushed 3 commits to feature/commit-activity-chart",
    date: "2026-08-27T14:22:00Z",
  },
  {
    id: "activity-2",
    type: "pull_request",
    repository: "ui-primitives",
    description: "Merged pull request #481 Fix focus ring on nested dropdown menus",
    date: "2026-08-27T09:10:00Z",
  },
  {
    id: "activity-3",
    type: "pull_request",
    repository: "tailwind-theme-studio",
    description: "Opened pull request #480 Extract design tokens into CSS variables",
    date: "2026-08-26T16:30:00Z",
  },
  {
    id: "activity-4",
    type: "repository_created",
    repository: "internal-design-system",
    description: "Created repository internal-design-system",
    date: "2026-08-26T15:00:00Z",
  },
  {
    id: "activity-5",
    type: "issue",
    repository: "devanalytics-dashboard",
    description: "Opened issue #312 Commit activity chart overflows on narrow viewports",
    date: "2026-08-26T09:20:00Z",
  },
  {
    id: "activity-6",
    type: "commit",
    repository: "go-worker-pool",
    description: "Pushed 1 commit to feat/benchmarks",
    date: "2026-08-26T08:31:00Z",
  },
  {
    id: "activity-7",
    type: "pull_request",
    repository: "rust-cli-scaffolder",
    description: "Merged pull request #478 Document the public API surface",
    date: "2026-08-25T19:15:00Z",
  },
  {
    id: "activity-8",
    type: "issue",
    repository: "tailwind-theme-studio",
    description: "Opened issue #310 Token export drops the alpha channel",
    date: "2026-08-24T18:45:00Z",
  },
  {
    id: "activity-9",
    type: "commit",
    repository: "portfolio-site",
    description: "Pushed 2 commits to fix/mobile-spacing",
    date: "2026-08-24T21:04:00Z",
  },
  {
    id: "activity-10",
    type: "pull_request",
    repository: "devanalytics-dashboard",
    description: "Opened pull request #475 Memoize recharts tooltip payloads",
    date: "2026-08-24T13:00:00Z",
  },
  {
    id: "activity-11",
    type: "repository_created",
    repository: "data-viz-playground",
    description: "Created repository data-viz-playground",
    date: "2026-08-23T10:00:00Z",
  },
  {
    id: "activity-12",
    type: "issue",
    repository: "go-worker-pool",
    description: "Opened issue #309 Worker pool leaks goroutines under heavy load",
    date: "2026-08-23T20:05:00Z",
  },
];
