import type { Repository } from "@/lib/types";

export const mockRepositories: Repository[] = [
  {
    id: "repo-1",
    name: "devanalytics-dashboard",
    fullName: "demo-developer/devanalytics-dashboard",
    description:
      "A professional developer analytics dashboard built with Next.js, Tailwind CSS and Recharts.",
    language: "TypeScript",
    stars: 1284,
    forks: 142,
    openIssues: 23,
    visibility: "public",
    updatedAt: "2026-08-27T14:32:00Z",
    topics: ["nextjs", "analytics", "dashboard", "tailwind"],
    url: "https://github.com/demo-developer/devanalytics-dashboard",
  },
  {
    id: "repo-2",
    name: "ui-primitives",
    fullName: "demo-developer/ui-primitives",
    description:
      "Accessible, unstyled React component primitives with a focus on keyboard navigation.",
    language: "TypeScript",
    stars: 892,
    forks: 76,
    openIssues: 11,
    visibility: "public",
    updatedAt: "2026-08-25T09:15:00Z",
    topics: ["react", "accessibility", "components"],
    url: "https://github.com/demo-developer/ui-primitives",
  },
  {
    id: "repo-3",
    name: "tailwind-theme-studio",
    fullName: "demo-developer/tailwind-theme-studio",
    description:
      "Visual editor for designing and exporting Tailwind CSS design tokens.",
    language: "JavaScript",
    stars: 637,
    forks: 54,
    openIssues: 8,
    visibility: "public",
    updatedAt: "2026-08-22T18:40:00Z",
    topics: ["tailwindcss", "design-tokens", "theme"],
    url: "https://github.com/demo-developer/tailwind-theme-studio",
  },
  {
    id: "repo-4",
    name: "rust-cli-scaffolder",
    fullName: "demo-developer/rust-cli-scaffolder",
    description:
      "Opinionated scaffolding tool for bootstrapping Rust command line applications.",
    language: "Rust",
    stars: 421,
    forks: 33,
    openIssues: 5,
    visibility: "public",
    updatedAt: "2026-08-19T11:05:00Z",
    topics: ["rust", "cli", "scaffolding"],
    url: "https://github.com/demo-developer/rust-cli-scaffolder",
  },
  {
    id: "repo-5",
    name: "portfolio-site",
    fullName: "demo-developer/portfolio-site",
    description:
      "Personal portfolio and blog built with Next.js App Router and MDX.",
    language: "TypeScript",
    stars: 318,
    forks: 47,
    openIssues: 3,
    visibility: "public",
    updatedAt: "2026-08-21T20:10:00Z",
    topics: ["nextjs", "mdx", "portfolio"],
    url: "https://github.com/demo-developer/portfolio-site",
  },
  {
    id: "repo-6",
    name: "data-viz-playground",
    fullName: "demo-developer/data-viz-playground",
    description:
      "Experiments with D3, Recharts and canvas-based visualization techniques.",
    language: "Python",
    stars: 256,
    forks: 28,
    openIssues: 6,
    visibility: "public",
    updatedAt: "2026-08-15T13:22:00Z",
    topics: ["dataviz", "d3", "python"],
    url: "https://github.com/demo-developer/data-viz-playground",
  },
  {
    id: "repo-7",
    name: "internal-design-system",
    fullName: "demo-developer/internal-design-system",
    description:
      "Company design system: components, tokens and usage guidelines.",
    language: "TypeScript",
    stars: 0,
    forks: 0,
    openIssues: 14,
    visibility: "private",
    updatedAt: "2026-08-26T16:48:00Z",
    topics: ["design-system", "internal"],
    url: "https://github.com/demo-developer/internal-design-system",
  },
  {
    id: "repo-8",
    name: "go-worker-pool",
    fullName: "demo-developer/go-worker-pool",
    description:
      "Lightweight, configurable worker pool for concurrent background jobs in Go.",
    language: "Go",
    stars: 534,
    forks: 61,
    openIssues: 9,
    visibility: "public",
    updatedAt: "2026-08-18T07:30:00Z",
    topics: ["go", "concurrency", "workers"],
    url: "https://github.com/demo-developer/go-worker-pool",
  },
  {
    id: "repo-9",
    name: "css-grid-cheatsheet",
    fullName: "demo-developer/css-grid-cheatsheet",
    description:
      "Interactive reference for modern CSS layout with copy-paste examples.",
    language: "CSS",
    stars: 743,
    forks: 88,
    openIssues: 4,
    visibility: "public",
    updatedAt: "2026-08-12T10:00:00Z",
    topics: ["css", "grid", "reference"],
    url: "https://github.com/demo-developer/css-grid-cheatsheet",
  },
  {
    id: "repo-10",
    name: "vue-storefront-kit",
    fullName: "demo-developer/vue-storefront-kit",
    description:
      "Starter kit for building fast e-commerce storefronts with Vue and Nuxt.",
    language: "Vue",
    stars: 399,
    forks: 41,
    openIssues: 7,
    visibility: "public",
    updatedAt: "2026-08-10T15:25:00Z",
    topics: ["vue", "nuxt", "ecommerce"],
    url: "https://github.com/demo-developer/vue-storefront-kit",
  },
];
